### ISSUE TITLE
Language name ‘Norwegian’ is incorrect

### ISSUE THREAD

**Issue by huftis** [cyntss/opensuse-landing-page#28]
The drop-down box for choosing language uses the name ‘Norwegian’ for the ‘nn’ translation. This is incorrect/misleading. The name should be ‘Norwegian Nynorsk’.

Some background: Norway has *two* official languages, Norwegian Nynorsk and Norwegian Bokmål. There is no written language called just ‘Norwegian’. The current translation is for Norwegian Nynorsk (language code: nn). (There is currently no translations into Norwegian Bokmål (language code: nb), but this may be added in the future.)

**Comment by Evalle** [comment]
Hi @huftis, thank you for your message. I can see that on 'old' opensuse page (https://www.opensuse.org/en/) there is *Norwegian Bokmål* language in drop-down box. 
ping @cyntss @ddemaio I can create a PR with fix if you OK with that.

**Comment by cyntss** [comment]
Yes perfect ! I am not familiar at all with the correct denomination of the language but what @huftis says makes sense.

@Evalle if you want to create the PR please do it. I can also do it if you dont have time :)

**Comment by Evalle** [comment]
@cyntss fixed in https://github.com/cyntss/opensuse-landing-page/pull/31 :)
