### ISSUE TITLE
yast link

### ISSUE THREAD

**Issue by jreidinger** [cyntss/opensuse-landing-page#30]
Hi,
very nice new landing page. I am just not sure if we should point for yast to https://en.opensuse.org/Portal:YaST which is a bit old, but still contain the most information or to newer but not complete http://yast.github.io/

Josef

**Comment by manugupt1** [comment]
Why not incorporate this as part of the main theme and the openSUSE infrastructure?

**Comment by cyntss** [comment]
Thank you for reporting this issue. In fact, we had both links ..one in the image and another in the actual link.. Bad Bad.. now it is fixed :+1:
