### ISSUE TITLE
Make this project our real landing page.

### ISSUE THREAD

**Issue by tigerfoot** [cyntss/opensuse-landing-page#33]
Hi @cyntss , yesterday we discuss about the status of publishing the project to www.o.o

So roughly the idea is to create a PR from this project (so we can have the associated git log)
We (board) know that you're not that technical versed people, especially when it come to play making PR against the real infrastructure.

If you don't mind, you could add myself as at least member with commit rights to this repository.
Once done, I would propose to organize the PR to move this content to the real repository
https://github.com/openSUSE/www.o.o and make anything possible to get it online

Any thoughts?

**Comment by aspiers** [comment]
+1, this is great work and it makes sense to use it!

I have reviewed the site and IMHO it is very very close to being ready but I think there are still a few minor tweaks needed.  I have submitted some pull requests and issues to this github project for them.

P.S. I have a lot of experience with `git` so if anyone needs help, just let me know.

**Comment by cyntss** [comment]
@tigerfoot I added you as a collaborator :+1:
