### ISSUE TITLE
mention and link to Evergreen

### ISSUE THREAD

**Issue by aspiers** [cyntss/opensuse-landing-page#35]
Would be nice if the landing page mentioned and linked to [Evergreen](https://en.opensuse.org/openSUSE:Evergreen) somewhere.

**Comment by sysrich** [comment]
The evergreen team are currently considering discontinuing Evergreen as a result of Leap

I dont want us to draw too much attention to Evergreen while that possibility hangs over it.

**Comment by aspiers** [comment]
Oh OK :) Should we close this then, or wait for their decision?

**Comment by sysrich** [comment]
I'm happy either way - if we close it, we can always reopen and revisit it as the situation with Evergreen develops
