### ISSUE TITLE
Huge background SVG

### ISSUE THREAD

**Issue by sknorr** [cyntss/opensuse-landing-page#41]
bg_contribution.svg is about 2.7 MB large, but could probably be done in less than 10 KB, if it didn't embed all those JPGs. (It generally helps to create SVGs in Inkscape, as Adobe software very often adds all kinds of binary formats which unnecessarily increase file size.)

**Comment by cyntss** [comment]
Hi @sknorr . Unfortunately our designer uses Adobe software. I will try to compress it since you are right, we shouldnt have an svg as heavy as that since it just handles vectors inside.

**Comment by cyntss** [comment]
So it is crazy the way Illustrator works, but when I opened the file in Inkscape I found the Entire mockup design there. It was only displaying the green part, but the whole design was hidden in the document lol.

Now it is fixed and the file weighs only 4K

Thank you @sknorr for reporting this issue.

**Comment by sknorr** [comment]
Ah, ok. Great!

**Comment by kwwii** [comment]
In any case, we should not use SVG's with embedded pixmaps. Especially on the opensuse site. Exporting from illustrator will do this if we use filter effects and such. It's always better to make a pure vector svg AND clear the definitions in inkscape before saving it the last time.

**Comment by sknorr** [comment]
Sometimes even that does not help. :/

E.g. look at [the LibreOffice logo graphic used in 5.0](http://cgit.freedesktop.org/libreoffice/core/tree/icon-themes/galaxy/brand/flat_logo.svg)

There is an <i:pgf> block at the end that seems completely superfluous, but as far as I can tell, you cannot remove it with Inkscape. (Except maybe with the XML source editor.)
