### ISSUE TITLE
Bad colour contrast in links in Contribute Code / Hardware

### ISSUE THREAD

**Issue by pierre4l** [cyntss/opensuse-landing-page#44]
When I click either the Code or Hardware links at the bottom of the landing page, the resulting overlay is semi-transparent against a green background, but the text box underneath the paragraph of text is a turquoise colour and almost impossible to see until hovering over it, where it turns white.

Same effect on both FF40.0.3 and Konqueror, on oS 13.1 64-bit.

**Comment by pierre4l** [comment]
screenshot: http://susepaste.org/63365011

**Comment by cyntss** [comment]
Thank you @pierre4l for sending the issue. I have just fixed it in commit: https://github.com/cyntss/opensuse-landing-page/commit/d1fec6f47dde58b16a02c69ca17f8f8e16a434c3
