### ISSUE TITLE
Chrome opensuse-laptop.jpg overflow

### ISSUE THREAD

**Issue by erleeman** [cyntss/opensuse-landing-page#45]
The jpg overflowing viewport in Chrome (Android + Desktop).

**Comment by cyntss** [comment]
I think this only happens in small devices right? I will fix it straight away ;)

**Comment by erleeman** [comment]
Yes, on my Z3 Compact.
I played a bit with the Chrome viewport:
990x till 768x the jpg is hidden.
Smaller 768x the jpg is visible.

Just one media querie missing ;-)

Thx

**Comment by cyntss** [comment]
It was a small bug when I replaced the png file to a compressed jpg. The class was there but it was not replaced in the .less file.
now it is fixed. I will be live as soon as we push to the server.. thank you for reporting it :+1:
