### ISSUE TITLE
german translation of Leap description sounds pessimistic

### ISSUE THREAD

**Issue by cboltz** [cyntss/opensuse-landing-page#50]
The german translation of the Leap description sounds pessimistic ;-)

"... openSUSE's latest regular-release version" was translated to "... openSUSEs letzter regulär veröffentlicher Version", which means the _very last_ version (as in "we won't do another one").

Please replace "letzter" with "neuester" or maybe "aktueller".

**Comment by cyntss** [comment]
@cboltz could you open a PR changing the translation? I am not a native german speaker so I dont dare to do this change since the original translations were provided by german people from the community.

**Comment by cyntss** [comment]
Please include the issue: https://github.com/cyntss/opensuse-landing-page/issues/51 as well in the PR. :+1:

**Comment by cyntss** [comment]
Fixed in https://github.com/cyntss/opensuse-landing-page/pull/60
