### ISSUE TITLE
mixed content warnings because of fonts.googleapis.com

### ISSUE THREAD

**Issue by cboltz** [cyntss/opensuse-landing-page#53]
The fonts.googleapis.com CSS is embedded over http, while the page itsself uses https. This leads to warnings about mixed content.

**Comment by cyntss** [comment]
@cboltz I recon this has been solved but I would like to ask you to close the issue if you consider it resolved, otherwise I will revisit this.

**Comment by cboltz** [comment]
Indeed, that's fixed in the meantime :-)
