### ISSUE TITLE
 Catalan language instead Ukrainian.

### ISSUE THREAD

**Issue by andriykopanytsia** [cyntss/opensuse-landing-page#59]
Hello!
The file opensuse-landing-page.uk.po and others files are fully translated in Ukrainian. Moreover, there is a correct Ukrainian langpack for searchpage on https://github.com/openSUSE/searchPage/tree/master/assets/js/langpack/uk.json and for landing page on 
https://github.com/cyntss/opensuse-landing-page/blob/master/assets/js/langpack/uk.json. 
Perhaps, there is a bug in the code of  www.opensuse.org and https://www.opensuse.org/searchPage/  because if I choose the Ukrainian language then the English text is replaced by the Catalan instead the Ukrainian.
I attached 2 screenshots for  www.opensuse.org and https://www.opensuse.org/searchPage/ .
![opensuse-landing-page-uk-ca](https://cloud.githubusercontent.com/assets/1636926/10020577/549f7598-614c-11e5-82cd-c67b62d06690.png)
![opensuse-search-page-uk-ca](https://cloud.githubusercontent.com/assets/1636926/10020578/549ff4f0-614c-11e5-91af-b36c8001aeea.png)

**Comment by Evalle** [comment]
Hello @andriykopanytsia thank you for the information. I will try to find out what's wrong here.

**Comment by Evalle** [comment]
Fixed in https://github.com/cyntss/opensuse-landing-page/pull/62 
ping @cyntss

**Comment by andriykopanytsia** [comment]
Thank you!

**Comment by cyntss** [comment]
@Evalle thank you for fixing this :+1:
